# Generated by Django 5.1.1 on 2024-10-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_descripcion_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Mueble', 'Mueble'), ('Decoración', 'Decoración'), ('Colgante', 'Colgante'), ('Temporada', 'Temporada')], default='opcion1', max_length=20),
        ),
    ]
