# Generated by Django 5.1.1 on 2024-10-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Mueble', 'Mueble'), ('Decoración', 'Decoración'), ('Colgante', 'Colgante'), ('Temporada', 'Temporada'), ('Más', 'Más')], default='Más', max_length=20),
        ),
    ]
