# Generated by Django 5.1.1 on 2024-10-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_producto_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='sku',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='productos_imagenes/imagenes/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='productos_imagenes/imagenes/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='productos_imagenes/portada/'),
        ),
    ]
