# Generated by Django 5.1.1 on 2024-10-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_remove_producto_imagen_remove_producto_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='acabado',
            field=models.CharField(default='Sin acabado', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(default='Natural', max_length=30),
        ),
        migrations.AddField(
            model_name='producto',
            name='dimensiones',
            field=models.CharField(default='Sin especificar', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_madera',
            field=models.CharField(choices=[('Roble', 'Roble'), ('Pino', 'Pino'), ('Cedro', 'Cedro'), ('Nogal', 'Nogal'), ('Bambú', 'Bambú'), ('Otro', 'Otro')], default='Otro', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=0, help_text='Precio en pesos chilenos (CLP)', max_digits=10),
        ),
    ]
